# Generated by Django 4.2.7 on 2025-10-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='name',
            field=models.CharField(max_length=1024, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='tagcategory',
            name='slug',
            field=models.SlugField(max_length=1024, unique=True),
        ),
    ]
