# Generated by Django 4.2.7 on 2025-10-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_name_alter_tag_slug_alter_tagcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name ru'),
        ),
        migrations.AddField(
            model_name='tagcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name ru'),
        ),
    ]
