# Generated by Django 4.2.7 on 2025-10-15 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('journal_conference', models.CharField(max_length=255, verbose_name='Journal/Conference')),
                ('publication_date', models.DateField(verbose_name='Publication Date')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('abstract', models.TextField(blank=True, verbose_name='Abstract')),
                ('keywords', models.JSONField(blank=True, default=list, verbose_name='Keywords')),
                ('citation_count', models.PositiveIntegerField(default=0, verbose_name='Citations')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='ai_modules.aimodule')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_date'],
                'indexes': [models.Index(fields=['publication_date'], name='publication_publica_1eb6f0_idx'), models.Index(fields=['doi'], name='publication_doi_6c08dc_idx')],
            },
        ),
    ]
