# Generated by Django 4.2.7 on 2025-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_publication_added_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='citation_count',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='keywords',
        ),
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=models.TextField(blank=True, verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='journal_conference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Journal/Conference'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.DateField(blank=True, verbose_name='Publication Date'),
        ),
    ]
