# Generated by Django 4.2.7 on 2025-10-27 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0009_alter_aimodule_company_alter_aimodule_country_and_more'),
        ('publications', '0003_remove_publication_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='ai_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='ai_modules.aimodule', verbose_name='AI Module'),
        ),
    ]
