# Generated by Django 4.2.7 on 2025-10-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('approve', 'Approved'), ('reject', 'Rejected'), ('block', 'Blocked'), ('unblock', 'Unblocked'), ('like', 'Liked'), ('unlike', 'Unliked')], max_length=20),
        ),
    ]
