# Generated by Django 4.2.7 on 2025-10-15 20:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('company', models.CharField(max_length=255, verbose_name='Company')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('params_count', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parameters Count')),
                ('task_short_description', models.TextField(max_length=500, verbose_name='Short Description')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('on_review', 'On Review'), ('active', 'Active'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_description', models.TextField(blank=True, max_length=300)),
                ('search_vector', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_modules', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'AI Module',
                'verbose_name_plural': 'AI Modules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIModuleDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Description')),
                ('technical_info', models.TextField(verbose_name='Technical Information')),
                ('architecture', models.TextField(blank=True, verbose_name='Architecture')),
                ('training_data_description', models.TextField(blank=True, verbose_name='Training Data Description')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='Metrics')),
                ('license_info', models.TextField(blank=True, verbose_name='License Information')),
                ('supported_languages', models.JSONField(blank=True, default=list)),
                ('requirements', models.TextField(blank=True, verbose_name='System Requirements')),
                ('ai_module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='ai_modules.aimodule')),
            ],
            options={
                'verbose_name': 'AI Module Details',
                'verbose_name_plural': 'AI Module Details',
            },
        ),
        migrations.CreateModel(
            name='AIModuleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ai_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='ai_modules.aimodule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Module Like',
                'verbose_name_plural': 'AI Module Likes',
                'unique_together': {('user', 'ai_module')},
            },
        ),
        migrations.CreateModel(
            name='AIModuleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file', models.FileField(upload_to='ai_modules/files/%Y/%m/', verbose_name='File')),
                ('file_type', models.CharField(choices=[('doc', 'Documentation'), ('model', 'Model File'), ('dataset', 'Dataset'), ('code', 'Code'), ('other', 'Other')], default='other', max_length=10, verbose_name='File Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('size', models.PositiveIntegerField(blank=True, null=True, verbose_name='File Size (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='ai_modules.aimodule')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by')),
            ],
            options={
                'verbose_name': 'AI Module File',
                'verbose_name_plural': 'AI Module Files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['ai_module', 'file_type'], name='ai_modules__ai_modu_021a60_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='aimodule',
            index=models.Index(fields=['status', 'created_at'], name='ai_modules__status_e538c2_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodule',
            index=models.Index(fields=['country'], name='ai_modules__country_c2f19d_idx'),
        ),
        migrations.AddIndex(
            model_name='aimodule',
            index=models.Index(fields=['slug'], name='ai_modules__slug_2bdf64_idx'),
        ),
    ]
