# Generated by Django 4.2.7 on 2025-10-15 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodule',
            name='version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Version'),
        ),
    ]
