# Generated by Django 4.2.7 on 2025-10-15 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0002_aimodule_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodule',
            name='license_type',
            field=models.CharField(blank=True, help_text='Type of license, e.g., MIT, Apache 2.0', max_length=100, verbose_name='License Type'),
        ),
    ]
