# Generated by Django 4.2.7 on 2025-10-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0003_aimodule_license_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodule',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published At'),
        ),
    ]
