# Generated by Django 4.2.7 on 2025-10-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0004_aimodule_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimoduledetail',
            name='installation_guide',
            field=models.TextField(blank=True, verbose_name='Installation Guide'),
        ),
    ]
