# Generated by Django 4.2.7 on 2025-10-15 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0005_aimoduledetail_installation_guide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimoduledetail',
            name='license_info',
        ),
    ]
