# Generated by Django 4.2.7 on 2025-10-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0006_remove_aimoduledetail_license_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aimodule',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='aimodule',
            name='search_vector',
        ),
        migrations.RemoveField(
            model_name='aimoduledetail',
            name='architecture',
        ),
        migrations.RemoveField(
            model_name='aimoduledetail',
            name='installation_guide',
        ),
        migrations.RemoveField(
            model_name='aimoduledetail',
            name='metrics',
        ),
        migrations.RemoveField(
            model_name='aimoduledetail',
            name='requirements',
        ),
        migrations.RemoveField(
            model_name='aimoduledetail',
            name='supported_languages',
        ),
        migrations.RemoveField(
            model_name='aimoduledetail',
            name='training_data_description',
        ),
        migrations.AddField(
            model_name='aimoduledetail',
            name='ability',
            field=models.TextField(null=True, verbose_name='Ability for users'),
        ),
        migrations.AddField(
            model_name='aimoduledetail',
            name='registration_number',
            field=models.CharField(max_length=255, null=True, verbose_name='Registration number'),
        ),
        migrations.AddField(
            model_name='aimoduledetail',
            name='registration_system',
            field=models.CharField(max_length=255, null=True, verbose_name='Registration system'),
        ),
        migrations.AddField(
            model_name='aimoduledetail',
            name='status',
            field=models.CharField(max_length=255, null=True, verbose_name='Status'),
        ),
    ]
