# Generated by Django 4.2.7 on 2025-10-25 16:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0007_remove_aimodule_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodule',
            name='params_count',
            field=models.BigIntegerField(default=10000000000, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Parameters Count'),
        ),
    ]
