# Generated by Django 4.2.7 on 2025-10-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0008_alter_aimodule_params_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodule',
            name='company',
            field=models.CharField(max_length=1024, verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='aimodule',
            name='country',
            field=models.CharField(max_length=1024, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='aimodule',
            name='license_type',
            field=models.CharField(blank=True, help_text='Type of license, e.g., MIT, Apache 2.0', max_length=1024, verbose_name='License Type'),
        ),
        migrations.AlterField(
            model_name='aimodule',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='aimodule',
            name='slug',
            field=models.SlugField(max_length=1024, unique=True),
        ),
    ]
