# Generated by Django 4.2.7 on 2025-10-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0009_alter_aimodule_company_alter_aimodule_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodule',
            name='name_ru',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Name ru'),
        ),
    ]
