# Generated by Django 4.2.7 on 2025-10-28 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_modules', '0010_aimodule_name_ru'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimoduledetail',
            name='registration_number',
            field=models.CharField(max_length=1024, null=True, verbose_name='Registration number'),
        ),
    ]
