# Generated by Django 4.2.7 on 2025-10-29 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_country_code'),
        ('ai_modules', '0011_alter_aimoduledetail_registration_number'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='aimodule',
            new_name='ai_modules__country_c75277_idx',
            old_name='ai_modules__country_c2f19d_idx',
        ),
        migrations.AlterField(
            model_name='aimodule',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='common.country', verbose_name='Created by'),
        ),
    ]
